
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/GoalToUs
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #spl문장 볼 수 있음

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true